# -*- coding: utf-8 -*-
"""ExerciseXP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nb4w66w3fL3aJOLDbVViXG9vyeVXg3uP
"""

import random

def number_guessing_game():
    print("Welcome to the Number Guessing Game!")
    print("I'm thinking of a number between 1 and 100.")

    random_number = random.randint(1, 100)
    max_attempts = 7

    for attempt in range(1, max_attempts + 1):
        try:
            guess = int(input(f"Attempt {attempt}/{max_attempts}: Enter your guess: "))
        except ValueError:
            print("Invalid input. Please enter a whole number.")
            continue

        if guess < random_number:
            print("Too low!")
        elif guess > random_number:
            print("Too high!")
        else:
            print(f"Congratulations! You guessed the number {random_number} in {attempt} attempts!")
            return

    print(f"Sorry, you ran out of attempts! The number I was thinking of was {random_number}.")

# Run the game
number_guessing_game()