# -*- coding: utf-8 -*-
"""ExerciseXP3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nb4w66w3fL3aJOLDbVViXG9vyeVXg3uP
"""

print("1. Fonction difference:")
def difference(a, b):
    return a - b

print(f"difference(2,2) # {difference(2,2)}")
print(f"difference(0,2) # {difference(0,2)}")

print("\n2. Fonction print_day:")
def print_day(num):
    days = {1: "Sunday", 2: "Monday", 3: "Tuesday", 4: "Wednesday",
            5: "Thursday", 6: "Friday", 7: "Saturday"}
    return days.get(num)

print(f"print_day(4) # {print_day(4)}")
print(f"print_day(41) # {print_day(41)}")

print("\n3. Fonction last_element:")
def last_element(lst):
    if not lst:
        return None
    return lst[-1]

print(f"last_element([1,2,3,4]) # {last_element([1,2,3,4])}")
print(f"last_element([]) # {last_element([])}")

print("\n4. Fonction number_compare:")
def number_compare(num1, num2):
    if num1 > num2:
        return "Le premier est plus grand"
    elif num2 > num1:
        return "Le second est plus grand"
    else:
        return "Les nombres sont égaux."

print(f"number_compare(1,1) # {number_compare(1,1)}")
print(f"number_compare(1,2) # {number_compare(1,2)}")
print(f"number_compare(2,1) # {number_compare(2,1)}")

print("\n5. Fonction single_letter_count:")
def single_letter_count(word, letter):
    return word.lower().count(letter.lower())

print(f"single_letter_count('amazing','A') # {single_letter_count('amazing','A')}")
print(f"single_letter_count('hello','z') # {single_letter_count('hello','z')}")

print("\n6. Fonction multiple_letter_count:")
def multiple_letter_count(string):
    return {char: string.count(char) for char in string}

print(f"multiple_letter_count(\"hello\") # {multiple_letter_count(\"hello\")}")
print(f"multiple_letter_count(\"person\") # {multiple_letter_count(\"person\")}")

print("\n7. Fonction list_manipulation:")
def list_manipulation(lst, command, location, value=None):
    if command == "remove":
        if location == "end":
            if lst: return lst.pop()
        elif location == "beginning":
            if lst: return lst.pop(0)
    elif command == "add":
        if location == "beginning":
            lst.insert(0, value)
            return lst
        elif location == "end":
            lst.append(value)
            return lst
    return None

list1 = [1,2,3]
print(f"list_manipulation([1,2,3], \"remove\", \"end\") # {list_manipulation(list1.copy(), 'remove', 'end')}")
list2 = [1,2,3]
print(f"list_manipulation([1,2,3], \"remove\", \"beginning\") # {list_manipulation(list2.copy(), 'remove', 'beginning')}")
list3 = [1,2,3]
print(f"list_manipulation([1,2,3], \"add\", \"beginning\", 20) # {list_manipulation(list3.copy(), 'add', 'beginning', 20)}")
list4 = [1,2,3]
print(f"list_manipulation([1,2,3], \"add\", \"end\", 30) # {list_manipulation(list4.copy(), 'add', 'end', 30)}")

print("\n8. Fonction is_palindrome:")
def is_palindrome(string):
    cleaned_string = "".join(char.lower() for char in string if char.isalnum())
    return cleaned_string == cleaned_string[::-1]

print(f"is_palindrome('a man a plan a canal Panama') # {is_palindrome('a man a plan a canal Panama')}")
print(f"is_palindrome('testing') # {is_palindrome('testing')}")
print(f"is_palindrome('tacocat') # {is_palindrome('tacocat')}")
print(f"is_palindrome('hannah') # {is_palindrome('hannah')}")
print(f"is_palindrome('robert') # {is_palindrome('robert')}")

print("\n9. Fonction frequency:")
def frequency(lst, search_term):
    return lst.count(search_term)

print(f"frequency([1,2,3,4,4,4], 4) # {frequency([1,2,3,4,4,4], 4)}")
print(f"frequency([True, False, True, True], False) # {frequency([True, False, True, True], False)}")

print("\n10. Fonction flip_case:")
def flip_case(phrase, letter):
    return "".join([char.swapcase() if char.lower() == letter.lower() else char for char in phrase])

print(f"flip_case(\"Hardy har har\", \"h\") # {flip_case(\"Hardy har har\", \"h\")}")

print("\n11. Fonction multiply_even_numbers:")
def multiply_even_numbers(lst):
    product = 1
    found_even = False
    for num in lst:
        if num % 2 == 0:
            product *= num
            found_even = True
    return product if found_even else 1 # If no even numbers, product remains 1

print(f"multiply_even_numbers([2,3,4,5,6]) # {multiply_even_numbers([2,3,4,5,6])}")
print(f"multiply_even_numbers([1,3,5]) # {multiply_even_numbers([1,3,5])}")

print("\n12. Fonction mode:")
from collections import Counter
def mode(lst):
    counts = Counter(lst)
    return counts.most_common(1)[0][0]

print(f"mode([2,4,1,2,3,3,4,4,5,4,4,6,4,6,7,4]) # {mode([2,4,1,2,3,3,4,4,5,4,4,6,4,6,7,4])}")

print("\n13. Fonction capitalize:")
def capitalize(string):
    if not string: return ""
    return string[0].upper() + string[1:]

print(f"capitalize(\"tim\") # {capitalize(\"tim\")}")
print(f"capitalize(\"matt\") # {capitalize(\"matt\")}")
print(f"capitalize(\"\") # {capitalize(\"\")}")

print("\n14. Fonction compact:")
def compact(lst):
    return [item for item in lst if item]

print(f"compact([0,1,2,\"\",[], False, {}, None, \"All done\"]) # {compact([0,1,2,\"\",[], False, {}, None, \"All done\"]) }")

print("\n15. Fonction partition:")
def partition(lst, callback):
    true_list = []
    false_list = []
    for item in lst:
        if callback(item):
            true_list.append(item)
        else:
            false_list.append(item)
    return [true_list, false_list]

def is_even(num):
    return num % 2 == 0

print(f"partition([1,2,3,4], is_even) # {partition([1,2,3,4], is_even)}")

print("\n16. Fonction intersection:")
def intersection(list1, list2):
    return [item for item in list1 if item in list2]

print(f"intersection([1,2,3], [2,3,4]) # {intersection([1,2,3], [2,3,4])}")

print("\n17. Fonction once:")
def once(func):
    has_run = False
    result = None
    def wrapper(*args, **kwargs):
        nonlocal has_run, result
        if not has_run:
            has_run = True
            result = func(*args, **kwargs)
            return result
        return None
    return wrapper

def add(a,b):
    return a + b

one_addition = once(add)

print(f"one_addition(2,2) # {one_addition(2,2)}")
print(f"one_addition(2,2) # {one_addition(2,2)}")
print(f"one_addition(12,200) # {one_addition(12,200)}")

print("\nSuper bonus: Décorateur run_once:")
def run_once(func):
    def wrapper(*args, **kwargs):
        if not hasattr(wrapper, 'has_run'):
            wrapper.has_run = True
            wrapper.result = func(*args, **kwargs)
            return wrapper.result
        return None
    return wrapper

@run_once
def add_decorated(a,b):
    return a + b

print(f"add_decorated(2,2) # {add_decorated(2,2)}")
print(f"add_decorated(2,20) # {add_decorated(2,20)}")
print(f"add_decorated(12,20) # {add_decorated(12,20)}")

