# -*- coding: utf-8 -*-
"""ExerciseXP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nb4w66w3fL3aJOLDbVViXG9vyeVXg3uP
"""

print("1. Print all values:")
my_list_1 = [1, 2, 3, 4]
print([x for x in my_list_1])

print("\n2. Values multiplied by 20:")
my_list_2 = [1, 2, 3, 4]
print([x * 20 for x in my_list_2])

print("\n3. First letter of each word:")
my_list_3 = ["Elie", "Tim", "Matt"]
print([word[0] for word in my_list_3])

print("\n4. Even values:")
my_list_4 = [1, 2, 3, 4, 5, 6]
print([x for x in my_list_4 if x % 2 == 0])

print("\n5. Intersection of two lists:")
list_a = [1, 2, 3, 4]
list_b = [3, 4, 5, 6]
print([x for x in list_a if x in list_b])

print("\n6. Reversed and lowercase words:")
my_list_6 = ["Elie", "Tim", "Matt"]
print([word[::-1].lower() for word in my_list_6])

print("\n7. Common letters in two strings (as a sorted list of unique chars):")
str_a = "first"
str_b = "third"
print(sorted(list(set([char for char in str_a if char in str_b]))))

print("\n8. Numbers divisible by 12 between 1 and 100:")
print([x for x in range(1, 101) if x % 12 == 0])

print("\n9. String with vowels removed:")
my_string_9 = "amazing"
vowels = "aeiou"
print([char for char in my_string_9 if char.lower() not in vowels])

print("\n10. Generate [[0, 1, 2], [0, 1, 2], [0, 1, 2]]:")
print([[0, 1, 2] for _ in range(3)])

print("\n11. Generate 10x10 grid of 0-9:")
print([[j for j in range(10)] for _ in range(10)])