# -*- coding: utf-8 -*-
"""ExerciseXP2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nb4w66w3fL3aJOLDbVViXG9vyeVXg3uP
"""

print("1. Créer un dictionnaire à partir d'une liste de tuples:")
list_of_tuples = [("name", "Elie"), ("job", "Instructor")]
dict_from_list = {key: value for key, value in list_of_tuples}
print(dict_from_list)

print("\n2. Créer un dictionnaire à partir de deux listes en utilisant zip:")
keys_list = ["CA", "NJ", "RI"]
values_list = ["California", "New Jersey", "Rhode Island"]
dict_from_two_lists = {key: value for key, value in zip(keys_list, values_list)}
print(dict_from_two_lists)

print("\n3. Créer un dictionnaire avec les voyelles comme clés et 0 comme valeur:")
vowels = 'aeiou'
vowel_dict = {vowel: 0 for vowel in vowels}
print(vowel_dict)

print("\n4. Créer un dictionnaire avec la position de la lettre et la lettre de l'alphabet (A-Z):")
alphabet_dict = {i + 1: chr(65 + i) for i in range(26)}
print(alphabet_dict)

print("\nSuper bonus: Compter les voyelles dans une chaîne:")
sentence = "awesome sauce"
vowels = 'aeiou'
vowel_counts = {vowel: sentence.lower().count(vowel) for vowel in vowels}
print(vowel_counts)

